version: '3'

volumes:
  postgres_data_dev: {}

services:
  postgres:
    image: postgres:13.4
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=billsbear
      - POSTGRES_USER=billsbear
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
